show_debug_overlay(1);
global.selected_tower = noone;
global.moveable = false;
global.wave = 1;
global.progressWaves = true;
global.lastEnemy = noone;
global.spawn_rate = 0;
global.pausePhase = false;
global.progress = 0;
global.maxProgress = 0;
global.level = rmMainMenu;
global.timecoins = 0;